"""Initial migration with all tables

Revision ID: f512b5b44754
Revises: 
Create Date: 2025-12-02 11:58:18.642508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f512b5b44754'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS um")
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.Integer(), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=500), nullable=False),
    sa.Column('authority', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_index(op.f('ix_um_oauth_providers_id'), 'oauth_providers', ['id'], unique=False, schema='um')
    op.create_table('um_authorizations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_arrival_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('authorization_number', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('member_name', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('healthplan_id', sa.String(length=100), nullable=False),
    sa.Column('health_plan', sa.String(length=200), nullable=False),
    sa.Column('requesting_npi', sa.String(length=20), nullable=False),
    sa.Column('requesting_name', sa.String(length=200), nullable=False),
    sa.Column('servicing_name', sa.String(length=200), nullable=True),
    sa.Column('template_type', sa.String(length=100), nullable=False),
    sa.Column('receipt_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_of_care', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('assigned_user', sa.String(length=200), nullable=True),
    sa.Column('procedure_code', sa.String(length=500), nullable=True),
    sa.Column('determination', sa.String(length=50), nullable=True),
    sa.Column('md_determination', sa.String(length=50), nullable=True),
    sa.Column('escalation_date', sa.DateTime(), nullable=True),
    sa.Column('escalation_type', sa.String(length=50), nullable=True),
    sa.Column('nurse_reviewer', sa.String(length=200), nullable=True),
    sa.Column('original_reviewer', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('complexity', sa.String(length=20), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    schema='um'
    )
    op.create_table('um_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    schema='um'
    )
    op.create_table('um_diagnosis_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id'),
    schema='um'
    )
    op.create_table('um_health_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.String(length=50), nullable=False),
    sa.Column('organization_marketing_name', sa.String(length=255), nullable=False),
    sa.Column('geographic_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id'),
    schema='um'
    )
    op.create_table('um_procedure_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('group_description', sa.String(length=255), nullable=True),
    sa.Column('code_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id'),
    schema='um'
    )
    op.create_table('um_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi'),
    schema='um'
    )
    op.create_table('um_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_key', sa.String(length=100), nullable=False),
    sa.Column('role_display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_key'),
    schema='um'
    )
    op.create_table('um_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=30), nullable=True),
    sa.Column('createddate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name'),
    schema='um'
    )
    op.create_table('um_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_index(op.f('ix_um_um_users_email'), 'um_users', ['email'], unique=True, schema='um')
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_key', sa.String(length=100), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_key'),
    schema='um'
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=False),
    sa.Column('creatorid', sa.String(length=30), nullable=False),
    sa.Column('createddate', sa.DateTime(), nullable=False),
    sa.Column('createddate_as_number', sa.Numeric(), nullable=True),
    sa.Column('lastupdateid', sa.String(length=30), nullable=False),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=False),
    sa.Column('lastupdatedate_as_number', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['um.um_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_index(op.f('ix_um_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False, schema='um')
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['um.oauth_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['um.um_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_index(op.f('ix_um_oauth_tokens_id'), 'oauth_tokens', ['id'], unique=False, schema='um')
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=255), nullable=False),
    sa.Column('permission_code', sa.String(length=255), nullable=True),
    sa.Column('permission_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=False),
    sa.Column('creatorid', sa.String(length=100), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=False),
    sa.Column('createddate_as_number', sa.Integer(), nullable=True),
    sa.Column('lastupdateid', sa.String(length=100), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=False),
    sa.Column('lastupdatedate_as_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['um.modules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_key'),
    schema='um'
    )
    op.create_table('role_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['um.um_roles.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['um.workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_table('um_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['um.um_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['um.um_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['um.um_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.String(length=1), nullable=True),
    sa.Column('creatorid', sa.String(length=50), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('createddate_as_number', sa.String(length=14), nullable=True),
    sa.Column('lastupdateid', sa.String(length=50), nullable=True),
    sa.Column('lastupdatedate', sa.DateTime(), nullable=True),
    sa.Column('lastupdatedate_as_number', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['um.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['um.um_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='um'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions', schema='um')
    op.drop_table('user_sessions', schema='um')
    op.drop_table('um_user_roles', schema='um')
    op.drop_table('role_workflows', schema='um')
    op.drop_table('permissions', schema='um')
    op.drop_index(op.f('ix_um_oauth_tokens_id'), table_name='oauth_tokens', schema='um')
    op.drop_table('oauth_tokens', schema='um')
    op.drop_index(op.f('ix_um_activity_logs_user_id'), table_name='activity_logs', schema='um')
    op.drop_table('activity_logs', schema='um')
    op.drop_table('workflows', schema='um')
    op.drop_index(op.f('ix_um_um_users_email'), table_name='um_users', schema='um')
    op.drop_table('um_users', schema='um')
    op.drop_table('um_templates', schema='um')
    op.drop_table('um_roles', schema='um')
    op.drop_table('um_providers', schema='um')
    op.drop_table('um_procedure_codes', schema='um')
    op.drop_table('um_health_plans', schema='um')
    op.drop_table('um_diagnosis_codes', schema='um')
    op.drop_table('um_config', schema='um')
    op.drop_table('um_authorizations', schema='um')
    op.drop_index(op.f('ix_um_oauth_providers_id'), table_name='oauth_providers', schema='um')
    op.drop_table('oauth_providers', schema='um')
    op.drop_table('modules', schema='um')
    op.execute("DROP SCHEMA IF EXISTS um")
    # ### end Alembic commands ###
